create table SYMPOSIUM_Report (
	uuid_ VARCHAR(75) null,
	reportId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	reportName VARCHAR(75) null,
	reportStatus VARCHAR(75) null,
	startTime DATE null,
	endTime DATE null,
	sectionSummary BOOLEAN,
	sectionSummaryStatus VARCHAR(75) null,
	sectionCosts BOOLEAN,
	sectionCostsStatus VARCHAR(75) null,
	sectionROI BOOLEAN,
	sectionROIStatus VARCHAR(75) null,
	sectionMetrics BOOLEAN,
	sectionMetricsStatus VARCHAR(75) null,
	sectionRecommendations BOOLEAN,
	sectionRecommendationsStatus VARCHAR(75) null
);