package com.liferay.symposium.portlet.report.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Report service. Represents a row in the &quot;SYMPOSIUM_Report&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.symposium.portlet.report.model.impl.ReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.symposium.portlet.report.model.impl.ReportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Report
 * @see com.liferay.symposium.portlet.report.model.impl.ReportImpl
 * @see com.liferay.symposium.portlet.report.model.impl.ReportModelImpl
 * @generated
 */
public interface ReportModel extends BaseModel<Report>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a report model instance should use the {@link Report} interface instead.
     */

    /**
     * Returns the primary key of this report.
     *
     * @return the primary key of this report
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this report.
     *
     * @param primaryKey the primary key of this report
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this report.
     *
     * @return the uuid of this report
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this report.
     *
     * @param uuid the uuid of this report
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the report ID of this report.
     *
     * @return the report ID of this report
     */
    public long getReportId();

    /**
     * Sets the report ID of this report.
     *
     * @param reportId the report ID of this report
     */
    public void setReportId(long reportId);

    /**
     * Returns the group ID of this report.
     *
     * @return the group ID of this report
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this report.
     *
     * @param groupId the group ID of this report
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this report.
     *
     * @return the company ID of this report
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this report.
     *
     * @param companyId the company ID of this report
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this report.
     *
     * @return the user ID of this report
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this report.
     *
     * @param userId the user ID of this report
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this report.
     *
     * @return the user uuid of this report
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this report.
     *
     * @param userUuid the user uuid of this report
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this report.
     *
     * @return the user name of this report
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this report.
     *
     * @param userName the user name of this report
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this report.
     *
     * @return the create date of this report
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this report.
     *
     * @param createDate the create date of this report
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this report.
     *
     * @return the modified date of this report
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this report.
     *
     * @param modifiedDate the modified date of this report
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the report name of this report.
     *
     * @return the report name of this report
     */
    @AutoEscape
    public String getReportName();

    /**
     * Sets the report name of this report.
     *
     * @param reportName the report name of this report
     */
    public void setReportName(String reportName);

    /**
     * Returns the report status of this report.
     *
     * @return the report status of this report
     */
    @AutoEscape
    public String getReportStatus();

    /**
     * Sets the report status of this report.
     *
     * @param reportStatus the report status of this report
     */
    public void setReportStatus(String reportStatus);

    /**
     * Returns the start time of this report.
     *
     * @return the start time of this report
     */
    public Date getStartTime();

    /**
     * Sets the start time of this report.
     *
     * @param startTime the start time of this report
     */
    public void setStartTime(Date startTime);

    /**
     * Returns the end time of this report.
     *
     * @return the end time of this report
     */
    public Date getEndTime();

    /**
     * Sets the end time of this report.
     *
     * @param endTime the end time of this report
     */
    public void setEndTime(Date endTime);

    /**
     * Returns the section summary of this report.
     *
     * @return the section summary of this report
     */
    public boolean getSectionSummary();

    /**
     * Returns <code>true</code> if this report is section summary.
     *
     * @return <code>true</code> if this report is section summary; <code>false</code> otherwise
     */
    public boolean isSectionSummary();

    /**
     * Sets whether this report is section summary.
     *
     * @param sectionSummary the section summary of this report
     */
    public void setSectionSummary(boolean sectionSummary);

    /**
     * Returns the section summary status of this report.
     *
     * @return the section summary status of this report
     */
    @AutoEscape
    public String getSectionSummaryStatus();

    /**
     * Sets the section summary status of this report.
     *
     * @param sectionSummaryStatus the section summary status of this report
     */
    public void setSectionSummaryStatus(String sectionSummaryStatus);

    /**
     * Returns the section costs of this report.
     *
     * @return the section costs of this report
     */
    public boolean getSectionCosts();

    /**
     * Returns <code>true</code> if this report is section costs.
     *
     * @return <code>true</code> if this report is section costs; <code>false</code> otherwise
     */
    public boolean isSectionCosts();

    /**
     * Sets whether this report is section costs.
     *
     * @param sectionCosts the section costs of this report
     */
    public void setSectionCosts(boolean sectionCosts);

    /**
     * Returns the section costs status of this report.
     *
     * @return the section costs status of this report
     */
    @AutoEscape
    public String getSectionCostsStatus();

    /**
     * Sets the section costs status of this report.
     *
     * @param sectionCostsStatus the section costs status of this report
     */
    public void setSectionCostsStatus(String sectionCostsStatus);

    /**
     * Returns the section r o i of this report.
     *
     * @return the section r o i of this report
     */
    public boolean getSectionROI();

    /**
     * Returns <code>true</code> if this report is section r o i.
     *
     * @return <code>true</code> if this report is section r o i; <code>false</code> otherwise
     */
    public boolean isSectionROI();

    /**
     * Sets whether this report is section r o i.
     *
     * @param sectionROI the section r o i of this report
     */
    public void setSectionROI(boolean sectionROI);

    /**
     * Returns the section r o i status of this report.
     *
     * @return the section r o i status of this report
     */
    @AutoEscape
    public String getSectionROIStatus();

    /**
     * Sets the section r o i status of this report.
     *
     * @param sectionROIStatus the section r o i status of this report
     */
    public void setSectionROIStatus(String sectionROIStatus);

    /**
     * Returns the section metrics of this report.
     *
     * @return the section metrics of this report
     */
    public boolean getSectionMetrics();

    /**
     * Returns <code>true</code> if this report is section metrics.
     *
     * @return <code>true</code> if this report is section metrics; <code>false</code> otherwise
     */
    public boolean isSectionMetrics();

    /**
     * Sets whether this report is section metrics.
     *
     * @param sectionMetrics the section metrics of this report
     */
    public void setSectionMetrics(boolean sectionMetrics);

    /**
     * Returns the section metrics status of this report.
     *
     * @return the section metrics status of this report
     */
    @AutoEscape
    public String getSectionMetricsStatus();

    /**
     * Sets the section metrics status of this report.
     *
     * @param sectionMetricsStatus the section metrics status of this report
     */
    public void setSectionMetricsStatus(String sectionMetricsStatus);

    /**
     * Returns the section recommendations of this report.
     *
     * @return the section recommendations of this report
     */
    public boolean getSectionRecommendations();

    /**
     * Returns <code>true</code> if this report is section recommendations.
     *
     * @return <code>true</code> if this report is section recommendations; <code>false</code> otherwise
     */
    public boolean isSectionRecommendations();

    /**
     * Sets whether this report is section recommendations.
     *
     * @param sectionRecommendations the section recommendations of this report
     */
    public void setSectionRecommendations(boolean sectionRecommendations);

    /**
     * Returns the section recommendations status of this report.
     *
     * @return the section recommendations status of this report
     */
    @AutoEscape
    public String getSectionRecommendationsStatus();

    /**
     * Sets the section recommendations status of this report.
     *
     * @param sectionRecommendationsStatus the section recommendations status of this report
     */
    public void setSectionRecommendationsStatus(
        String sectionRecommendationsStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.symposium.portlet.report.model.Report report);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.symposium.portlet.report.model.Report> toCacheModel();

    @Override
    public com.liferay.symposium.portlet.report.model.Report toEscapedModel();

    @Override
    public com.liferay.symposium.portlet.report.model.Report toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
