package com.liferay.symposium.portlet.report.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.symposium.portlet.report.model.Report;
import com.liferay.symposium.portlet.report.service.ReportLocalServiceUtil;

/**
 * The extended model base implementation for the Report service. Represents a row in the &quot;SYMPOSIUM_Report&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReportImpl
 * @see com.liferay.symposium.portlet.report.model.Report
 * @generated
 */
public abstract class ReportBaseImpl extends ReportModelImpl implements Report {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a report model instance should use the {@link Report} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReportLocalServiceUtil.addReport(this);
        } else {
            ReportLocalServiceUtil.updateReport(this);
        }
    }
}
